ignore_branches:
    - gh-pages

pre_composer_script: |
    #!/bin/bash

    # Do what you need to setup your project
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/secret:.*/secret: KUMhgyfC5W7z6qgQSpnjxBpI1bTkKCPS/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash

    # Do what you need to configure your project
    #./app/console doctrine:database:create --no-interaction
    #./app/console doctrine:schema:create --no-interaction
    #./app/console doctrine:fixtures:load --no-interaction

php_ini: |
    ;extension=openssl.so
    ;extension=mcrypt.so
