imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    doctrine.orm.metadata.driver_chain.class: Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain

framework:
    esi:             { enabled: true }
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        SID
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        less:
            apply_to: "\.less$"
        cssrewrite:
            apply_to:
                - "\.less$"
                - "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: pmd_doctrine.orm_mapping.naming_strategy_underscore

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sensio Framework Extra Configuration
sensio_framework_extra:
    view: { annotations: false }

# FOS Rest Configuration
fos_rest:
    body_listener: true
    format_listener: true
    view:
        view_response_listener: "force"

# PMD Frontend Configuration
pmd_frontend:
    listeners:
        view_listener:
            view_priority: 128
            view_attribute: "_frontend[view]"
            vars_attribute: "_frontend[vars]"

# PMD State Machine Configuration
pmd_state_machine:
    definitions:
        invoice_management:
            states:
                registered:
                    transitions:
                        accept: accepted
                        correct: corrected
                        cancel: canceled

                corrected:
                    transitions:
                        cancel: canceled
                        pay: paid
                        expiry: expired

                accepted:
                    transitions:
                        pay: paid
                        expiry: expired

                paid:
                    transitions:
                        remove: removed

                canceled:
                    transitions:
                        remove: removed

                removed:
                    transitions: ~

                expired:
                    transitions:
                        pay: paid
