security:
    access_decision_manager:
        allow_if_all_abstain: true

    providers:
        in_memory:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
